version: '3.1'
services:
  mariadb:
    image: mariadb
    container_name: travel-mariadb
    restart: always
    environment:
      MYSQL_USER: travel
      MYSQL_ROOT_PASSWORD: traveller
      MYSQL_DATABASE: traverller
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    container_name: travel-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
